FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app


COPY *.csproj  ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .

RUN useradd -m myelevaiuser
USER myelevaiuser

CMD ASPNETCORE_URLS="http://*:$PORT" dotnet ElevaApi.dll